import 'package:dime/controllers/consultant/blog/my_blog_controller.dart';
import 'package:get/get.dart';
import '../controllers/auth/change_password_controller.dart';
import '../controllers/auth/forget_password_controller.dart';
import '../controllers/auth/sign_in_controller.dart';
import '../controllers/auth/sign_up_controller.dart';

import '../controllers/consultant/appointment_history_controller.dart';
import '../controllers/consultant/blog/upload_blog_controller.dart';
import '../controllers/consultant/info/personal_information_controller.dart';
import '../controllers/consultant/info/added_experience_controller.dart';
import '../controllers/consultant/info/availability_controller.dart';
import '../controllers/consultant/info/identification_controller.dart';
import '../controllers/consultant/info/professional_qualifications_controller.dart';
import '../controllers/consultant/patients_details/patients_details_controller.dart';
import '../controllers/consultant/patients_info/appointment_list_controller.dart';
import '../controllers/consultant/patients_info/doctor_home_controller.dart';
import '../controllers/consultant/patients_info/patients_list_controller.dart';
import '../controllers/consultant/profile/doctor_profile.dart';
import '../controllers/consultant/transaction/withdraw_controller.dart';
import '../controllers/user/Booking/book_appointment_controller.dart';
import '../controllers/user/Booking/booking_details_controller.dart';
import '../controllers/user/Booking/ambulance_booking_controller.dart';
import '../controllers/user/Booking/home_care_controller.dart';
import '../controllers/user/Booking/lab_booking_controller.dart';
import '../controllers/user/Booking/my_booking_controller.dart';
import '../controllers/user/Booking/shhedule_reply_controller.dart';
import '../controllers/user/blog/blogs_controller.dart';
import '../controllers/user/category_list_controller.dart';
import '../controllers/user/chat/chat_controller.dart';
import '../controllers/user/chat/video_call_controller.dart';
import '../controllers/user/consultant_details_controller.dart';
import '../controllers/user/health_rocords_controller.dart';
import '../controllers/user/home_controller.dart';
import '../controllers/user/chat/message_controller.dart';
import '../controllers/user/notifications_controller.dart';
import '../controllers/user/payment/payment_controller.dart';
import '../controllers/user/payment/select_payment_method_controller.dart';
import '../controllers/user/profile_controller.dart';
import '../controllers/user/send_review_controller.dart';
import '../controllers/user/setting/privacy_policy_controller.dart';
import '../controllers/user/setting/setting_controller.dart';
import '../controllers/user/setting/terms_of_services_controller.dart';


class DependencyInjection extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => SignUpController(), fenix: true);
    Get.lazyPut(() => HomeControllerPatients(), fenix: true);
    Get.lazyPut(() => BookAppointmentController(), fenix: true);
    Get.lazyPut(() => MyBookingController(), fenix: true);
    Get.lazyPut(() => MessageController(), fenix: true);
    Get.lazyPut(() => SendReviewController(), fenix: true);
    Get.lazyPut(() => LabBookingController(), fenix: true);
    Get.lazyPut(() => HomeCareController(), fenix: true);
    Get.lazyPut(() => AmbulanceBookingController(), fenix: true);
    Get.lazyPut(() => NotificationsController(), fenix: true);
    Get.lazyPut(() => ProfileController(), fenix: true);
    Get.lazyPut(() => HealthRecordController(), fenix: true);
    Get.lazyPut(() => SettingController(), fenix: true);
    Get.lazyPut(() => PersonalInformationController(), fenix: true);
    Get.lazyPut(() => ProfessionalQualificationsController(), fenix: true);
    Get.lazyPut(() => AddedExperienceController(), fenix: true);
    Get.lazyPut(() => AvailabilityController(), fenix: true);
    Get.lazyPut(() => IdentificationController(), fenix: true);
    Get.lazyPut(() => DoctorHomeController(), fenix: true);
    Get.lazyPut(() => PatientsListController(), fenix: true);
    Get.lazyPut(() => AppointmentListController(), fenix: true);
    Get.lazyPut(() => PatientsDetailsController(), fenix: true);
    Get.lazyPut(() => DoctorProfileController(), fenix: true);
    Get.lazyPut(() => AppointmentHistoryController(), fenix: true);
    Get.lazyPut(() => ForgetPasswordController(), fenix: true);
    Get.lazyPut(() => SignInController(), fenix: true);
    Get.lazyPut(() => CategoryListController(), fenix: true);
    Get.lazyPut(() => SelectPaymentMethodController(), fenix: true);
    Get.lazyPut(() => PaymentController(), fenix: true);
    Get.lazyPut(() => BookingDetailsController(), fenix: true);
    Get.lazyPut(() => UploadBlogController(), fenix: true);
    Get.lazyPut(() => MyBlogController(), fenix: true);
    Get.lazyPut(() => ChangePasswordController(), fenix: true);
    Get.lazyPut(() => ScheduleReplyController(), fenix: true);
    Get.lazyPut(() => ConsultantDetailsController(), fenix: true);
    Get.lazyPut(() => BlogsController(), fenix: true);
    Get.lazyPut(() => PrivacyPolicyController(), fenix: true);
    Get.lazyPut(() => TermsOfServicesController(), fenix: true);
    Get.lazyPut(() => ChatController(), fenix: true);
    Get.lazyPut(() => VideoCallController(), fenix: true);
    Get.lazyPut(() => WithdrawController(), fenix: true);
  }
}
